version: 1.0.9.5b{build}
image: Visual Studio 2022
configuration: Release
platform: x64
before_build:
- cmd: nuget restore
build:
  project: .\src\Shairport4w.vcxproj
  verbosity: minimal
artifacts:
  - path: .\x64\Debug\Shairport4wx64.exe
    name: Shairport4wx64
